# Generated by Django 5.2.5 on 2026-02-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school'),
        ),
    ]
