# Generated by Django 5.2.5 on 2026-02-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_admin_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='admin',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='Default School', max_length=200),
        ),
    ]
