# Generated by Django 5.2.5 on 2026-02-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attempt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='studenttest',
            name='taken_at',
        ),
    ]
