# Generated by Django 5.2.5 on 2026-02-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_studenttest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('class_name', 'test_name')},
        ),
        migrations.RemoveField(
            model_name='test',
            name='school',
        ),
    ]
